title: Saram Abbas | PhD student - AI in Oncology
description: >-
  PhD researcher developing explainable AI for bladder cancer recurrence. Published in Frontiers in Oncology and EMBC 2025. Passionate about transparent machine learning for real-world healthcare.
email:  # optional, can remove or add an address
github_username: saramabbas
minimal_mistakes_skin: default
search: true

url: "https://saramabbas.github.io"
baseurl: ""  # Needed for GitHub Pages user site

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Europe/London

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Saram Abbas"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "PhD in Explainable AI for Bladder Cancer"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://saramabbas.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saramabbas"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/saram-abbas/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saramabbas"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
